/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIpws_JNIpws */

#ifndef _Included_JNIpws_JNIpws
#define _Included_JNIpws_JNIpws
#ifdef __cplusplus
extern "C" {
#endif
#undef JNIpws_JNIpws_IDTYPE_SCENARIO
#define JNIpws_JNIpws_IDTYPE_SCENARIO 1L
#undef JNIpws_JNIpws_IDTYPE_HEADER
#define JNIpws_JNIpws_IDTYPE_HEADER 38L
#undef JNIpws_JNIpws_IDTYPE_AIRGROUP
#define JNIpws_JNIpws_IDTYPE_AIRGROUP 20L
#undef JNIpws_JNIpws_IDTYPE_PILOT
#define JNIpws_JNIpws_IDTYPE_PILOT 22L
#undef JNIpws_JNIpws_IDTYPE_AIRCRAFT
#define JNIpws_JNIpws_IDTYPE_AIRCRAFT 32L
#undef JNIpws_JNIpws_IDTYPE_TF
#define JNIpws_JNIpws_IDTYPE_TF 70L
#undef JNIpws_JNIpws_IDTYPE_SHIPCLASS
#define JNIpws_JNIpws_IDTYPE_SHIPCLASS 27L
#undef JNIpws_JNIpws_IDTYPE_DEVICE
#define JNIpws_JNIpws_IDTYPE_DEVICE 31L
#undef JNIpws_JNIpws_IDTYPE_LOCATION
#define JNIpws_JNIpws_IDTYPE_LOCATION 19L
#undef JNIpws_JNIpws_IDTYPE_SHIP
#define JNIpws_JNIpws_IDTYPE_SHIP 8L
#undef JNIpws_JNIpws_IDTYPE_MINES
#define JNIpws_JNIpws_IDTYPE_MINES 30L
#undef JNIpws_JNIpws_IDTYPE_LEADER
#define JNIpws_JNIpws_IDTYPE_LEADER 21L
#undef JNIpws_JNIpws_IDTYPE_PLAYERPREF
#define JNIpws_JNIpws_IDTYPE_PLAYERPREF 45L
/*
 * Class:     JNIpws_JNIpws
 * Method:    jPWSOpenFile
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_JNIpws_JNIpws_jPWSOpenFile
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     JNIpws_JNIpws
 * Method:    jPWSGetNextItem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIpws_JNIpws_jPWSGetNextItem
  (JNIEnv *, jobject);

/*
 * Class:     JNIpws_JNIpws
 * Method:    jPWSCloseFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIpws_JNIpws_jPWSCloseFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
